// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIzLMLKy5l-yut0XI-zthOIhpWOA6mlBg',
    appId: '1:42653846877:web:14a4fda06050a3feb26cb4',
    messagingSenderId: '42653846877',
    projectId: 'tchat-df6e9',
    authDomain: 'tchat-df6e9.firebaseapp.com',
    storageBucket: 'tchat-df6e9.firebasestorage.app',
    measurementId: 'G-E13Z0HED1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsh9MZ2rngNxNlvCEVSzQVrCr_fdKb7-M',
    appId: '1:42653846877:android:33880b8fb3375e89b26cb4',
    messagingSenderId: '42653846877',
    projectId: 'tchat-df6e9',
    storageBucket: 'tchat-df6e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-OpQw2hNUpMaqPeVfh7i_fyPFXMWsomk',
    appId: '1:42653846877:ios:724a5e60878a5daab26cb4',
    messagingSenderId: '42653846877',
    projectId: 'tchat-df6e9',
    storageBucket: 'tchat-df6e9.firebasestorage.app',
    iosBundleId: 'com.example.appChatDesktop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-OpQw2hNUpMaqPeVfh7i_fyPFXMWsomk',
    appId: '1:42653846877:ios:724a5e60878a5daab26cb4',
    messagingSenderId: '42653846877',
    projectId: 'tchat-df6e9',
    storageBucket: 'tchat-df6e9.firebasestorage.app',
    iosBundleId: 'com.example.appChatDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIzLMLKy5l-yut0XI-zthOIhpWOA6mlBg',
    appId: '1:42653846877:web:57b391385dca80ceb26cb4',
    messagingSenderId: '42653846877',
    projectId: 'tchat-df6e9',
    authDomain: 'tchat-df6e9.firebaseapp.com',
    storageBucket: 'tchat-df6e9.firebasestorage.app',
    measurementId: 'G-0T47MR7HR1',
  );
}
